University/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using University.Models;

namespace University.Controllers
{
    public class UploadController : Controller
    {
        pesEntities db = new pesEntities();
        public JsonResult FetchPropertyTypes(string customerType) // its a GET, not a POST
        {
            // In reality you will do a database query based on the value of provinceId, but based on the code you have shown
            if (customerType == "1" || customerType == "3")
            {
                string[] types = { "Residential building", "Condominium", "Apartment", "Vehicle" };
                var names = from p in db.luPropertyTypes
                            where types.Contains(p.Type)
                            orderby p.Type
                            select new
                            {
                                p.Id,
                                p.Type
                            }; ;



                return Json(names, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var names = from p in db.luPropertyTypes
                            orderby p.Type
                            select new
                            {
                                p.Id,
                                p.Type
                            }; ;



                return Json(names, JsonRequestBehavior.AllowGet);
            }
           
        }
        // GET: Upload
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            else
            {
                List<UploadedDocument> docs = (from d in db.UploadedDocuments
                                               where d.EstimationRequestId == id.Value
                                               select d).ToList();
                EstimationRequest er = (from e in db.EstimationRequests
                                        where e.Id == id
                                        select e).FirstOrDefault();
                TempData["requestid"] = id;
                TempData["branch"] = er.RequestingBranch;
                TempData["applicant"] = er.ApplicantName;
                TempData["date"] = er.DateUploaded.ToString("MMM dd,yyyy");
                return View(docs);
            }
            
        }
         public ActionResult Upload(int? id)
        {

            if (id == null)
            {
                return HttpNotFound();
            }
            else
            {
                TempData["requestId"] = id;
                EstimationRequest er= (from e in db.EstimationRequests where e.Id==id select e).FirstOrDefault();
                TempData["branch"] = er.RequestingBranch;
                TempData["applicant"] = er.ApplicantName;
                TempData["requestdate"] = er.DateUploaded.ToString("MMM dd, yyyy");
                List<string> uploadedDocuments = (from u in db.UploadedDocuments
                                                  where u.EstimationRequestId == id
                                                  select u.luDocumentType.Name).ToList();
                if (uploadedDocuments.Contains("Other"))
                {
                    string otherRemark = (from u in db.UploadedDocuments
                                               where u.EstimationRequestId == id
                                               where u.DocumentTypeId == 6
                                               select u.Remark).FirstOrDefault();
                    int itemindex=uploadedDocuments.IndexOf("Other");
                    uploadedDocuments[itemindex] += "_" + otherRemark;

                }
                ViewBag.UploadedDocuments = uploadedDocuments;
                int[] documenttypes=new int[]{1,2,3,4,5,6,7,8,9,10};
                if(er.CustomerType==1 && (er.PropertyType==1 ||  er.PropertyType==2 ||  er.PropertyType==3)) //If customer is SLA && property type is residntial,condominium or appartment
  {
  documenttypes=new int[]{1,2,3,4,5,6};
  }
  else if(er.CustomerType==1 && er.PropertyType==7) //If customer is SLA && property type is vehicle
  {
  documenttypes=new int[]{1,2,3,7,5,6};
  
  }
  else if(er.CustomerType==2 && (er.PropertyType==1 || er.PropertyType==2 || er.PropertyType==3 || er.PropertyType==4 || er.PropertyType==5 || er.PropertyType==6)) //If customer is Business && property type is not vehicle or machinery
  {
    documenttypes=new int[]{2,3,4,6};

 
  }
   else if(er.CustomerType==2 && er.PropertyType==7) //If customer is Business && property type is vehicle
  {
     documenttypes=new int[]{ 2,3,7,6};

  }
    else if(er.CustomerType==2 && er.PropertyType==8) //If customer is Business && property type is machinery
  {
       documenttypes=new int[]{ 2,3,8,9,6};
  }

    else if(er.CustomerType==3 && (er.PropertyType==1 || er.PropertyType==2 || er.PropertyType==3)) //If customer is zemen staff && property type is residential,cond or apartment
  {
         documenttypes=new int[]{ 10,2,4,5,6};
  }

    else if(er.CustomerType==3 && er.PropertyType==7) //If customer is zemen staff && property type is vehicle
  {
      documenttypes = new int[] { 10, 2, 7, 5, 6 };
 
  }

                List<int> uploaded = (from u in db.UploadedDocuments
                                      where u.EstimationRequestId == id
                                      select u.DocumentTypeId).ToList();

                ViewBag.DocumentTypeId = new SelectList(db.luDocumentTypes.Where(d => documenttypes.Contains(d.Id)).Where(u => !uploaded.Contains(u.Id)).OrderBy(b => b.Name), "Id", "Name");
                return View();
            }

        }
        [HttpPost]
         public JsonResult Upload()
         {

             int reqid = int.Parse(Request["EstimationRequestId"]);
             int requestid = int.Parse(Request["EstimationRequestId"]);
             EstimationRequest er = (from e in db.EstimationRequests where e.Id == requestid select e).FirstOrDefault();
             if (Request.Files["File"].ContentLength > 0)
             {
                 //string name = Convert.ToString(Session["LogedUserID"]);
                 string extension = System.IO.Path.GetExtension(Request.Files["File"].FileName);
                 string FileName = requestid + "_" + Request["DocumentTypeId"]+extension;

                 string path1 = string.Format("{0}/{1}", Server.MapPath(@"~\Content\UploadedDocuments\"), (FileName));
                 if (System.IO.File.Exists(FileName))
                 {
                     System.IO.File.Delete(FileName);

                 }
                 try
                 {
                     UploadedDocument ud = new UploadedDocument();
                     ud.EstimationRequestId = requestid;
                     ud.FilePath = "../Content/UploadedDocuments/" + FileName;
                     ud.DocumentTypeId = int.Parse(Request["DocumentTypeId"]);
                     ud.Remark = ud.DocumentTypeId == 6 ? Request["Remark"] : "";
                     db.UploadedDocuments.Add(ud);
                     db.SaveChanges();
                     Request.Files["File"].SaveAs(path1);

                     if (checkDocumentStatus(requestid))
                     {
                        
                         er.Status = 2;
                         er.DateUploaded = DateTime.Now;
                         db.Entry(er).State = EntityState.Modified;
                         db.SaveChanges();
                         List<int> groups = new List<int>(){1,5};
                         List<string> receivers = (from e in db.Users where groups.Contains(e.UserGroup) select e.UserName).ToList();
                         foreach (string receiver in receivers)
                         {
                             string subject = "New valuation request received";
                             string to = receiver + "@zemenbank.com";
                             string message = "<b>Dear " + receiver + "</b>,<br /> Valuation is requested by " + er.RequestingBranch + " for " + er.ApplicantName + ".<br /><ul><li>Property type : " + er.luPropertyType.Type + "</li><li>Customer type : " + er.luCustomerType.Type + "</li><li>Address: " + er.EstimationAddress1 + ", " + er.EstimationAddress2 + "</li></ul>";
                             sendEmail(to, subject, message);
                         }
                     }
                     else
                     {
                         
                         er.Status = 1;
                         db.Entry(er).State = EntityState.Modified;
                         db.SaveChanges();
                     }

                 }
                 catch
                 {
                     return Json("Error Occured while processing your request. Please try again.");
                     
                 }
                 List<string> uploadedDocuments = (from u in db.UploadedDocuments
                                                   where u.EstimationRequestId == requestid
                                                   select u.luDocumentType.Name).ToList();
                 string doclist = "";
                 if (uploadedDocuments.Contains("Other"))
                 {
                     string otherRemark = (from u in db.UploadedDocuments
                                           where u.EstimationRequestId == requestid
                                           where u.DocumentTypeId == 6
                                           select u.Remark).FirstOrDefault();
                     int itemindex = uploadedDocuments.IndexOf("Other");
                     uploadedDocuments[itemindex] += "_" + otherRemark;

                 }
                 if (uploadedDocuments.Count() > 0)
                 {
                     doclist+="<ul>";

University/Views/Upload/Assign.cshtml
@{
    ViewBag.Title = "Valuation Request";
    Layout = null;
}
<style type="text/css">
    .tblForm td {
        height: 28px;
    }
</style>
@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", id = "assignRequest", onsubmit = "return validateForm()" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true)
   
    

    <input type="hidden" name="EstimationRequestId" id="EstimationRequestId" value='@TempData["requestid"]' />
    <div style="color:red">
        @{
    if (TempData["ErrorMEssage"] != null)
    {
        Write(TempData["ErrorMEssage"]);
    }
        }
    </div>
    @Html.Raw(TempData["requestinfo"])
    <table align="center" style="color:black" class="tblForm">
        <tr>
            <td><b>Assign To: &nbsp;</b></td>
            <td>
                @{
                    if(TempData["assignedto"] == null || TempData["assignedto"].ToString()==""){
                        @Html.DropDownList("userid","")<br />
                }
                    else{
                        @Html.DropDownList("userid")<br />

                    }
                }
            </td>
            <td><div id="useridmsg" style="color:red"></div></td>
        </tr>
        <tr>
            <td><b>Valuation Date: &nbsp;</b></td>
            <td>
                <input type='text' class="date-picker" name='ValuationDate' id='ValuationDate' value='@DateTime.Today.ToString("MM/dd/yyyy")' readonly />
            </td>
            <td></td>
        </tr>
        <tr>
            <td><b>Valuation Time: &nbsp;</b></td>
            <td>
                <select id="ValuationTime"><option>Morning</option><option>Afternoon</option></select>
            </td>
            <td></td>
        </tr>






        <tr>
            <td colspan="3">
                <input type="button" value="   Assign   " class="linkEffect" onclick="assign()" />
                <div id="status" style="color:blue"></div>
            </td>

        </tr>
    </table><br />
    <hr />
    
    




}
<script type="text/javascript">
  

        // This will make every element with the class "date-picker" into a DatePicker element
        $('.date-picker').datepicker({
            format: "mm/dd/yyyy",
            autoclose: true
        });


    

    function validateForm() {
        document.getElementById("useridmsg").innerHTML = "";
        if (document.getElementById("userid").value == "") {
            document.getElementById("useridmsg").innerHTML = "Select assigned user.";
            return false;
        }





        return true;

    }

    function assign() {
        document.getElementById("status").innerHTML = "";
        // Checking whether FormData is available in browser
        if (validateForm()) {

            // Create FormData object
            var fileData = new FormData();

            // Looping over all files and add it to FormData object

            fileData.append("userid", document.getElementById("userid").value);
            fileData.append("requestid", document.getElementById("EstimationRequestId").value);
            fileData.append("username", $("#userid option:selected").text());
            fileData.append("ValuationDate", document.getElementById("ValuationDate").value);
            fileData.append("ValuationTime", document.getElementById("ValuationTime").value);




            $.ajax({
                url: '../Upload/Assign',
                type: "POST",
                contentType: false, // Not to set any content header
                processData: false, // Not to process data
                data: fileData,
                success: function (result) {
                    if (result == "Error Occured while processing your request. Please try again.") {
                        document.getElementById("status").innerHTML = result;

                    }
                    else {

                        document.getElementById("status").innerHTML = "Success";
                    }
                    location.reload();

                },
                error: function (err) {
                    alert(err.statusText);
                }
            });
        } else {
            //alert("FormData is not supported.");
        }

    }


</script>

University/Views/Upload/ChangeDoc.cshtml
@{
    ViewBag.Title = "Valuation Request";
    Layout = null;
}
<style type="text/css">
    .tblForm td {
        height: 28px;
    }
</style>
@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", id = "changeDocument", onsubmit = "return validateForm()" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true)
    <div style="color:red">
        @{
    if (TempData["ErrorMEssage"] != null)
    {
        Write(TempData["ErrorMEssage"]);
    }
        }
    </div>
    <table align="center" style="color:black" class="tblForm">
         <tr>
            <td><b>File &nbsp;</b></td>
            <td>
                <input type="file" name="File" id="File" /><br />
            </td>
            <td><div style="color:red" id="filemsg"></div></td>
        </tr>
       

        <tr>
            <td colspan="3">
                <input type="button" value="   Change   " class="linkEffect" onclick="changeDocument()" />
                <div id="status" style="color:blue"></div>
            </td>

        </tr>
    </table><br />
    
    




}
<script>



   
    function validateForm() {
        document.getElementById("filemsg").innerHTML = "";
        var filePath = $("#File").val();
        var file_ext = filePath.substr(filePath.lastIndexOf('.') + 1, filePath.length);
        if (file_ext != "pdf" && file_ext != "PDF") {
            document.getElementById("filemsg").innerHTML = "Only pdf files are allowed.";
        return false;
        }

        



        return true;

    }

    function changeDocument() {
        document.getElementById("status").innerHTML = "";
        // Checking whether FormData is available in browser
        if (validateForm()) {
            var fileUpload = $("#File").get(0);
            var files = fileUpload.files;

            // Create FormData object
            var fileData = new FormData();

            // Looping over all files and add it to FormData object
            for (var i = 0; i < 1; i++) {
                fileData.append("File", files[i]);
            }

            // Adding one more key to FormData object
            fileData.append('path', '@(TempData["path"])');

            $.ajax({
                url: '../ChangeDoc',
                type: "POST",
                contentType: false, // Not to set any content header
                processData: false, // Not to process data
                data: fileData,
                success: function (result) {
                    if (result == "Error Occured while processing your request. Please try again.") {
                        document.getElementById("status").innerHTML = result;

                    }
            else{

                    document.getElementById("status").innerHTML = "Successfully changed document.";
            }

                },
                error: function (err) {
                    alert(err.statusText);
                }
            });
        } else {
            //alert("FormData is not supported.");
        }

    }


</script>

University/Views/Upload/CreateRequest.cshtml
@{
    ViewBag.Title = "Valuation Request";
    Layout = null;
}
<style type="text/css">
    .tblForm td { height: 28px; }
</style>
@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", id = "createRequest", onsubmit = "return validateForm()" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true)

    <div style="color:red">
        @{
    if (TempData["ErrorMEssage"] != null)
    {
        Write(TempData["ErrorMEssage"]);
    }
        }
    </div>
    <table align="center" style="color:black" class="tblForm">
        <tr>
            <td><b>Applicant Name &nbsp;</b></td>
            <td>
                <input type="text" name="ApplicantName" id="ApplicantName" /><br />
            </td>
            <td><div style="color:red" id="applicantnamemsg"></div></td>
        </tr>
        

        <tr>
            <td><b>Mortgager Name &nbsp;</b></td>
            <td>
                <input type="text" name="MortgagerName" id="MortgagerName" /><br />
            </td>
            <td><div style="color:red" id="mortgagernamemsg"></div></td>
        </tr>

        <tr>
            <td><b>Estimation Place &nbsp;</b></td>
            <td>
                <select name="EstimationAddress1" id="EstimationAddress1" >
                    <option>Addis Ababa</option><option>Afar Region</option><option>Amhara Region</option><option>Benishangul-Gumuz Region</option>
                    <option>Central Ethiopia Regional State</option><option>Dire Dawa</option><option>Gambela Region</option><option>Harari Region</option>
                    <option>Oromia Region</option><option>Sidama Region</option><option>Somali Region</option><option>South Ethiopia Regional State</option>
                    <option>South West Ethiopia Peoples Region</option><option>Tigray Region</option>
                </select>&nbsp;&nbsp;
                <textarea type="text" name="EstimationAddress2" id="EstimationAddress2" cols="30" rows="5"></textarea><br />
                <br />
            </td>
            <td><div style="color:red" id="estimationplacemsg"></div></td>
        </tr>

        <tr>
            <td><b>Customer Type &nbsp;</b></td>
            <td>
                @Html.DropDownList("CustomerType")<br />
            </td>
            <td></td>
        </tr>
        
        <tr>
            <td><b>Property Type &nbsp;</b></td>
            <td>
                @Html.DropDownList("PropertyType")<br />
            </td>
            <td></td>
        </tr>

        <tr>
            <td><b>Valuation Purpose &nbsp;</b></td>
            <td>
                @Html.DropDownList("ValuationPurpose")<br />
            </td>
            <td></td>
        </tr>


        <tr>
            <td><b>Hard Copy Files &nbsp;</b></td>
            <td>
                <textarea name="HardCopyFiles" id="HardCopyFiles" cols="30" rows="5"></textarea><br />
            </td>
            <td><div style="color:red" id="mortgagernamemsg"></div></td>
        </tr>
       
        <tr>
            <td>
                @{
    if (Session["UserGroup"].ToString() != "5")
    {
        WriteLiteral("<div style='display:none'>");

    }
                }
            <b>Hard Copy Status &nbsp;</b>
                @{
    if (Session["UserGroup"].ToString() != "5")
    {
        WriteLiteral("</div>");
    }
                }
            </td>
            <td>
                @{
    if (Session["UserGroup"].ToString() != "5")
    {
        WriteLiteral("<div style='display:none'>");

    }
                }
                <select><option></option><option>Submitted</option><option>Not Submitted</option></select><br />
                @{
    if (Session["UserGroup"].ToString() != "5")
    {
        WriteLiteral("</div>");
    }
                }
            </td>
            <td></td>
        </tr>
        <tr>
            <td>
                @{
    if (Session["UserGroup"].ToString() != "5")
    {
        WriteLiteral("<div style='display:none'>");

    }
                }
            <b>CSR Remark &nbsp;</b>
                @{
    if (Session["UserGroup"].ToString() != "5")
    {
        WriteLiteral("</div>");
    }
                }
            </td>
            <td>
                @{
    if (Session["UserGroup"].ToString() != "5")
    {
        WriteLiteral("<div style='display:none'>");

    }
                }
                <textarea name="CSRRemark" id="CSRRemark" cols="30" rows="5"></textarea><br />
                @{
    if (Session["UserGroup"].ToString() != "5")
    {
        WriteLiteral("</div>");
    }
                }
            </td>
            <td></td>
        </tr>
        <tr>
            <td>
                @{
    if (Session["UserGroup"].ToString() != "5")
    {
        WriteLiteral("<div style='display:none'>");

    }
                }
            <b>Estimation Report&nbsp;</b>
                @{
    if (Session["UserGroup"].ToString() != "5")
    {
        WriteLiteral("</div>");
    }
                }
            </td>
            <td>
                @{
    if (Session["UserGroup"].ToString() != "5")
    {
        WriteLiteral("<div style='display:none'>");

    }
                }
                <input type="file" name="EstimationReportDoc" id="EstimationReportDoc" /><input type="hidden" name="EstimationReport" id="EstimationReport" /><br /></td>
            @{
    if (Session["UserGroup"].ToString() != "5")
    {
        WriteLiteral("</div>");
    }
            }
            <td></td>
        </tr>
       
        <tr>
            <td colspan="3">
                <input type="submit" value="Request" class="linkEffect" style="border:0" />

            </td>

        </tr>
    </table>



}
<script>

    function validateForm() {



        if (document.getElementById("ApplicantName").value == "") {
            document.getElementById("applicantnamemsg").innerHTML = "Applicant name is required.";
            return false;
        }
        if (document.getElementById("MortgagerName").value == "") {
            document.getElementById("mortgagernamemsg").innerHTML = "Mortgager name is required.";
            return false;
        }
        if (document.getElementById("EstimationAddress2").value == "") {
            document.getElementById("estimationplacemsg").innerHTML = "Estimation Place is required.";
            return false;
        }


        return true;

    }
    function reloadPropertyTypes(x, customerType) {

        var url = '@Url.Action("FetchPropertyTypes", "Upload")'; // Don't hard code your url's!
        var names = $(x); // cache it
        var myObject = { customerType: customerType };
        //alert(JSON.stringify(myObject))
        $.getJSON(url, myObject, function (response) {
            names.empty(); // remove any existing options
            //names.append("<option></option>");
            var i = -1;
            $.each(response, function (res) {
                i++;
                names.append($("<option value='" + response[i].Id + "'>" + response[i].Type + "</option>"));

            });
        });

    }

    $('#CustomerType').change(function () {
        var customerType = document.getElementById("CustomerType").value;

        var x = "#PropertyType";
        //reloadTitle('#Position2');

        reloadPropertyTypes(x, customerType);
    });
</script>

University/Views/Upload/Evaluate.cshtml
@{
    ViewBag.Title = "Valuer Response";
    Layout = null;
}
<style type="text/css">
    .tblForm td {
        height: 28px;
    }
</style>
@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", id = "valuerResponse", onsubmit = "return validateForm()" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true)



    <input type="hidden" name="EstimationRequestId" id="EstimationRequestId" value='@TempData["requestid"]' />
    <div style="color:red">
        @{
    if (TempData["ErrorMEssage"] != null)
    {
        Write(TempData["ErrorMEssage"]);
    }
        }
    </div>
    @Html.Raw(TempData["requestinfo"])
    <table align="center" style="color:black" class="tblForm">
        <tr>
            <td><b>Status: &nbsp;</b></td>
            <td>
                @{
                    @Html.DropDownList("Status");
                }
            </td>
            <td></td>
        </tr>    
    <tr>
            <td><b>Response: &nbsp;</b></td>
            <td>
                
                <textarea id="ValuerRemark" name="ValuerRemark">@(TempData["ValuerRemark"])</textarea>
                            </td>
            <td><div id="responsemsg" style="color:red"></div></td>
        </tr>



        <tr>
            <td colspan="3">
                <input type="button" value="Save" class="linkEffect" style="margin-left:70px;margin-top:14px" onclick="respond()" />
                <div id="status2" style="color:blue"></div>
            </td>

        </tr>
    </table><br />
    <hr />






}
<script>


    function validateForm() {
        document.getElementById("responsemsg").innerHTML = "";
        if (document.getElementById("ValuerRemark").value == "") {
            document.getElementById("responsemsg").innerHTML = "Please fill response.";
        return false;
        }





        return true;

    }

    function respond() {
        document.getElementById("status2").innerHTML = "";
        // Checking whether FormData is available in browser
        if (validateForm()) {

            // Create FormData object
            var fileData = new FormData();

            // Looping over all files and add it to FormData object

            fileData.append("Status", document.getElementById("Status").value);
            fileData.append("ValuerRemark", document.getElementById("ValuerRemark").value);
            fileData.append("requestid", document.getElementById("EstimationRequestId").value);



            $.ajax({
                url: '../Upload/Evaluate',
                type: "POST",
                contentType: false, // Not to set any content header
                processData: false, // Not to process data
                data: fileData,
                success: function (result) {
                        document.getElementById("status2").innerHTML = result;
                    location.reload();

                },
                error: function (err) {
                    alert(err.statusText);
                }
            });
        } else {
            //alert("FormData is not supported.");
        }

    }


</script>

University/Views/Upload/FinalReport.cshtml
@{
    ViewBag.Title = "Valuation Request";
    Layout = null;
}
<style type="text/css">
    .tblForm td {
        height: 56px;
    }
</style>
@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data", id = "finalReport", onsubmit = "return validateForm()" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true)
    <input type="hidden" name="EstimationRequestId" id="EstimationRequestId" value='@TempData["requestId"]' />
    <div style="color:red">
        @{
    if (TempData["ErrorMEssage"] != null)
    {
        Write(TempData["ErrorMEssage"]);
    }
        }
    </div>
    <h2>Final report for valuation request by @TempData["branch"] for @TempData["applicant"] on @TempData["requestdate"]</h2>
    <table align="center" style="color:black;" class="tblForm">
        <tr>
            <td><b>Remark &nbsp;</b></td>
            <td>
                <textarea name="CSRRemark" id="CSRRemark">@(TempData["CSRRemark"])</textarea><br />
            </td>
            <td><div id="remarkmsg" style="color:red"></div></td>
        </tr>


        <tr>
            <td><b>Report &nbsp;</b></td>
            <td>
                <input type="file" name="File" id="File" /><br />
            </td>
            <td><div style="color:red" id="filemsg"></div></td>
        </tr>
        

        <tr>
            <td colspan="3">
                <input type="button" value="   Upload   " class="linkEffect" onclick="finalReport()" />
                <div id="status" style="color:blue"></div>
            </td>

        </tr>
    </table><br />
    <hr />
    <br />
    




}
<script>

        

    
    function validateForm() {
        document.getElementById("remarkmsg").innerHTML = "";
        document.getElementById("filemsg").innerHTML = "";
        var filePath = $("#File").val();
        var file_ext = "";
        if (filePath != "") {
        filePath.substr(filePath.lastIndexOf('.') + 1, filePath.length);
        }
        if (filePath != "" && file_ext != "pdf" && file_ext != "PDF") {
            document.getElementById("filemsg").innerHTML = "Only pdf files are allowed.";
        return false;
        }

        var csrRemark = document.getElementById("CSRRemark").value;
        if (csrRemark == "") { 
            document.getElementById("remarkmsg").innerHTML = "Please explain the final report you are trying to upload.";
        }


        



        return true;

    }

    function finalReport() {
        document.getElementById("status").innerHTML = "";
        // Checking whether FormData is available in browser
        if (validateForm()) {
            var fileUpload = $("#File").get(0);
            var files = fileUpload.files;

            // Create FormData object
            var fileData = new FormData();

            // Looping over all files and add it to FormData object
            for (var i = 0; i < 1; i++) {
                fileData.append("File", files[i]);
            }

            // Adding one more key to FormData object
            fileData.append('EstimationRequestId', document.getElementById('EstimationRequestId').value);
            fileData.append('CSRRemark', document.getElementById('CSRRemark').value);

            $.ajax({
                url: '../Upload/FinalReport',
                type: "POST",
                contentType: false, // Not to set any content header
                processData: false, // Not to process data
                data: fileData,
                success: function (result) {
                        document.getElementById("status").innerHTML = result;
                    

                },
                error: function (err) {
                    alert(err.statusText);
                }
            });
        } else {
            //alert("FormData is not supported.");
        }

    }


</script>